# Generated by Django 4.1 on 2022-10-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daftar_rs',
        ),
    ]
