# Generated by Django 4.1 on 2022-12-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Belum Tersedia', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Belum Tersedia', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(default='Belum Tersedia', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Belum Tersedia', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Belum Tersedia', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Belum Tersedia', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default='Belum Tersedia', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(default='Belum Tersedia', max_length=200),
        ),
    ]
