# Generated by Django 4.1 on 2022-10-28 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('umur', models.IntegerField()),
                ('gender', models.CharField(choices=[('laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=10)),
                ('gejala', models.CharField(choices=[('nogejala', 'Tanpa Gejala'), ('gejalasedang', 'Gejala Sedang'), ('gejalaberat', 'Gejala Berat')], max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
