# Generated by Django 4.1.2 on 2022-10-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('umur', models.IntegerField()),
                ('gender', models.CharField(choices=[('laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=10)),
                ('status', models.CharField(choices=[('nogejala', 'Tanpa Gejala'), ('gejalasedang', 'Gejala Sedang'), ('gejalaberat', 'Gejala Berat')], max_length=20)),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
    ]
