# Generated by Django 4.1 on 2022-10-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lurah_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapasien',
            name='is_gejala',
        ),
        migrations.AddField(
            model_name='datapasien',
            name='gejala',
            field=models.CharField(choices=[('nogejala', 'Tanpa Gejala'), ('gejalasedang', 'Gejala Sedang'), ('gejalaberat', 'Gejala Berat')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
