# Generated by Django 4.1.2 on 2022-10-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lurah_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasien',
            name='is_covid',
            field=models.BooleanField(default=True),
        ),
    ]
